### ISSUE TITLE
PyPI release doesn't work with sagemaker and PyYAML

### ISSUE THREAD

**Issue by tonyhoo** [autogluon/autogluon-cloud#90]
Steps to reproduce:
* Create new conda env with python 3.8-1.10
* pip install autogluon.cloud

Platform tested:
* MacOS with M1
* Amazon Linux 2

See stack trace:
```
(test)  ~/downloads/ pip install autogluon.cloud
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting autogluon.cloud
  Downloading autogluon.cloud-0.2.0-py3-none-any.whl (74 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 kB 4.8 MB/s eta 0:00:00
Collecting autogluon.common<1.0,>=0.7 (from autogluon.cloud)
  Obtaining dependency information for autogluon.common<1.0,>=0.7 from https://files.pythonhosted.org/packages/67/c7/aa2bd5708c9329a29245aa0cd955cace0662b92a82eb7605cf46b6e7e9d5/autogluon.common-0.8.2-py3-none-any.whl.metadata
  Downloading autogluon.common-0.8.2-py3-none-any.whl.metadata (11 kB)
Collecting boto3<2.0,>=1.10 (from autogluon.cloud)
  Obtaining dependency information for boto3<2.0,>=1.10 from https://files.pythonhosted.org/packages/af/9c/58ca26190a8b89776ec66fdf769d6d0d5287044417b58df4d8225a081153/boto3-1.28.42-py3-none-any.whl.metadata
  Downloading boto3-1.28.42-py3-none-any.whl.metadata (6.7 kB)
Collecting numpy<1.27,>=1.21 (from autogluon.cloud)
  Obtaining dependency information for numpy<1.27,>=1.21 from https://files.pythonhosted.org/packages/0f/a8/5057b97c395a710999b5697ffedd648caee82c24a29595952d26bd750155/numpy-1.25.2-cp39-cp39-macosx_11_0_arm64.whl.metadata
  Downloading numpy-1.25.2-cp39-cp39-macosx_11_0_arm64.whl.metadata (5.6 kB)
Collecting packaging<24.0,>=23.0 (from autogluon.cloud)
  Downloading packaging-23.1-py3-none-any.whl (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.9/48.9 kB 50.7 MB/s eta 0:00:00
Collecting pandas<1.6,>=1.4.1 (from autogluon.cloud)
  Downloading pandas-1.5.3-cp39-cp39-macosx_11_0_arm64.whl (11.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 55.7 MB/s eta 0:00:00
Collecting sagemaker<3.0,>=2.126.0 (from autogluon.cloud)
  Downloading sagemaker-2.184.0.tar.gz (884 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 884.6/884.6 kB 58.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pyarrow<11.1,>=11.0 (from autogluon.cloud)
  Downloading pyarrow-11.0.0-cp39-cp39-macosx_11_0_arm64.whl (22.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.4/22.4 MB 54.9 MB/s eta 0:00:00
Collecting PyYAML<5.5,>=3.10 (from autogluon.cloud)
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 20.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      /private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/opt/anaconda3/envs/test/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/anaconda3/envs/test/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/anaconda3/envs/test/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 1001, in run_command
          super().run_command(command)
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 318, in run
          self.find_sources()
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 326, in find_sources
          mm.run()
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 548, in run
          self.add_defaults()
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 586, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/command/sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 201, in get_source_files
        File "/private/var/folders/k4/95srbw_95xscbyf50zwwk9lm0000gr/T/pip-build-env-4lab7tmq/overlay/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

**Comment by Jwely** [comment]
This lib is unusable as recommended in [documentation](https://auto.gluon.ai/cloud/0.2.0/tutorials/autogluon-cloud.html) 

This issue with pyyaml: https://github.com/yaml/pyyaml/issues/601 is the root cause.

Scientists on my team had to drop this lib from their workflow entirely and only now am i understanding why. 

Workarounds include upgrade pyyaml, but when using `pyyaml==6.0.1` this lib forces  the broken versions with `Collecting PyYAML<5.5,>=3.10 (from autogluon-cloud)` anyway.

Another possible workaround is to downgrade Cython to < 3.0 and pyyaml to 5.3.1, but:

```
sagemaker 2.188.0 requires PyYAML~=6.0, but you have pyyaml 5.3.1 which is incompatible.
```

I haven't been able to find a workaround. Is an upgrade to pyyaml 6.0.1 here a trivial change?

**Comment by Jwely** [comment]
This lib is unusable as recommended in [documentation](https://auto.gluon.ai/cloud/0.2.0/tutorials/autogluon-cloud.html) 

This issue with pyyaml: https://github.com/yaml/pyyaml/issues/601 is the root cause.

Scientists on my team had to drop this lib from their workflow entirely and only now am i understanding why. 

Workarounds include upgrade pyyaml, but when using `pyyaml==6.0.1` this lib forces  the broken versions with `Collecting PyYAML<5.5,>=3.10 (from autogluon-cloud)` anyway.

Another possible workaround is to downgrade Cython to < 3.0 and pyyaml to 5.3.1, but:

```
sagemaker 2.188.0 requires PyYAML~=6.0, but you have pyyaml 5.3.1 which is incompatible.
```

I haven't been able to find a workaround. Is an upgrade to pyyaml 6.0.1 here a trivial change?

**Comment by Jwely** [comment]
This lib is unusable as recommended in [documentation](https://auto.gluon.ai/cloud/0.2.0/tutorials/autogluon-cloud.html) 

This issue with pyyaml: https://github.com/yaml/pyyaml/issues/601 is the root cause.

Scientists on my team had to drop this lib from their workflow entirely and only now am i understanding why. 

Workarounds include upgrade pyyaml, but when using `pyyaml==6.0.1` this lib forces  the broken versions with `Collecting PyYAML<5.5,>=3.10 (from autogluon-cloud)` anyway.

Another possible workaround is to downgrade Cython to < 3.0 and pyyaml to 5.3.1, but:

```
sagemaker 2.188.0 requires PyYAML~=6.0, but you have pyyaml 5.3.1 which is incompatible.
```

I haven't been able to find a workaround. Is an upgrade to pyyaml 6.0.1 here a trivial change?
