### ISSUE TITLE
Support custom metrics

### ISSUE THREAD

**Issue by tonyhoo** [autogluon/autogluon-cloud#96]
Currently, custom_metrics is supported for all modules in AutoGluon-1.0.0. However, we don't have such parameter supported in cloud module. The request is to add custom_metrics in cloud

**Comment by james-yun** [comment]
I followed the custom metric guide here: 
https://auto.gluon.ai/dev/tutorials/tabular/advanced/tabular-custom-metric.html

I tried both defining metric in same file and different file.

### My code:
```
from autogluon.cloud import TabularCloudPredictor

model_name = '1hr'

predictor_init_args = {
    'label': 'responder_6',
    'problem_type': 'regression',
    'eval_metric': ag_weighted_r2_custom_scorer,
    'path': f'AutogluonModels/${model_name}',
    'sample_weight': 'weight',
    'weight_evaluation': True,
}  # init args you would pass to AG TabularPredictor
predictor_fit_args = {
    "train_data": 'subsampled_train.csv', 
    # "time_limit": 120,
}  # fit args you would pass to AG TabularPredictor
cloud_predictor = TabularCloudPredictor(
    cloud_output_path="s3://jane-street-training"
).fit(
    predictor_init_args=predictor_init_args,
    predictor_fit_args=predictor_fit_args,
)
```

###

Output (same file):
```
Starting AG
Args: Namespace(output_data_dir='/opt/ml/output/data', model_dir='/opt/ml/model', n_gpus='0', train_dir='/opt/ml/input/data/train', tune_dir=None, train_images=None, tune_images=None, ag_args='/opt/ml/input/data/ag_args', serving_script='/opt/ml/input/data/serving')
Using ag_args.pkl
Traceback (most recent call last):
  File "/opt/ml/code/train.py", line 96, in <module>
ag_args = pickle.load(f)  # AutoGluon-specific args
^^^^^
^^^^^^^^^
AttributeError: Can't get attribute 'weighted_r2' on <module '__main__' from '/opt/ml/code/train.py'>
2024-12-27 04:18:25,944 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2024-12-27 04:18:25,944 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 1 from exiting process.
2024-12-27 04:18:25,944 sagemaker-training-toolkit ERROR    Reporting training FAILURE
2024-12-27 04:18:25,944 sagemaker-training-toolkit ERROR    ExecuteUserScriptError:
ExitCode 1
ErrorMessage "AttributeError: Can't get attribute 'weighted_r2' on <module '__main__' from '/opt/ml/code/train.py'>"
Command "/opt/conda/bin/python3.11 train.py"
2024-12-27 04:18:25,944 sagemaker-training-toolkit ERROR    Encountered exit_code 1
Training failed. Please check sagemaker console training jobs ag-cloudpredictor-1735272943-e9d0 for details.
```


```
Starting AG
Args: Namespace(output_data_dir='/opt/ml/output/data', model_dir='/opt/ml/model', n_gpus='0', train_dir='/opt/ml/input/data/train', tune_dir=None, train_images=None, tune_images=None, ag_args='/opt/ml/input/data/ag_args', serving_script='/opt/ml/input/data/serving')
Using ag_args.pkl
Traceback (most recent call last):
  File "/opt/ml/code/train.py", line 96, in <module>
ag_args = pickle.load(f)  # AutoGluon-specific args
^^^^^^^^
^^^^^^
ModuleNotFoundError: No module named 'my_metrics'
2024-12-27 04:24:55,759 sagemaker-training-toolkit INFO     Waiting for the process to finish and give a return code.
2024-12-27 04:24:55,759 sagemaker-training-toolkit INFO     Done waiting for a return code. Received 1 from exiting process.
2024-12-27 04:24:55,759 sagemaker-training-toolkit ERROR    Reporting training FAILURE
2024-12-27 04:24:55,759 sagemaker-training-toolkit ERROR    ExecuteUserScriptError:
ExitCode 1
ErrorMessage "ModuleNotFoundError: No module named 'my_metrics'"
Command "/opt/conda/bin/python3.11 train.py"
2024-12-27 04:24:55,759 sagemaker-training-toolkit ERROR    Encountered exit_code 1
```

Would be nice to have parity for this feature in AutoGluon Cloud.
